[build]
command = "npm run build"
publish = "dist"

[functions]
directory = "/netlify/functions"

[[redirects]]
from = "/zach-is-cool/"
to = "/.netlify/builders/zach-is-cool"
status = 200
force = true
_generated_by_eleventy_serverless = "events"
